headers:
  - 'Accept: application/json'

options:
  - '--compress'

url: http://localhost

endpoints:
  get_ip:
    path: /ip

  get_cpu_load:
    method: GET
    path: /cpu/{cpu}/load
    x-www-form-urlencoded:
      - core
      - temperature
    options:
      - '--silent'
    parameters:
      core: 1

  get_cpu_load_raw_query:
    method: GET
    path: /cpu/{cpu}/load
    query: core={core}&freq={freq}&temp={temp}&version={version}
    options:
      - '--silent'
    parameters:
      core: 1

  post_cpu_load:
    method: POST
    path: /cpu/{cpu}/load
    query:
      - version
      - type
    x-www-form-urlencoded: core={core}&freq={freq}
    parameters:
      version: 1

  put_cpu_load_limit:
    path: /cpu/{cpu}/load/{load}
    headers:
      - 'Content-length: 0'


requests:
  get_cpu0_load:
    endpoint: get_cpu_load
    cpu: 0
    core: 0
    freq: 1
    temp: 50
    version: 4

  full_local_cpu:
    endpoint: put_cpu_load_limit
    load: 100

  minimal_local_cpu:
    endpoint: put_cpu_load_limit
    load: 5
